# Generated by Django 6.0.4 on 2026-05-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('analise', 'Em análise'), ('alugado', 'Alugado'), ('inativo', 'Inativo')], default='disponivel', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.tipoimovel')),
            ],
        ),
    ]
