# Generated by Django 6.0.4 on 2026-05-07 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('retirada', 'Retirada'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
        ),
    ]
