# Generated by Django 6.0.4 on 2026-05-07 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_chave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=100)),
                ('telefone_cliente', models.CharField(blank=True, max_length=20)),
                ('acao', models.CharField(max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.chave')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
